//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public Citas()
        {
            this.Detalles_Cita = new HashSet<Detalles_Cita>();
        }
    
        public int idCita { get; set; }
        public int idDoctor { get; set; }
        public int idPaciente { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public bool Asistida { get; set; }
        public bool Active { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual ICollection<Detalles_Cita> Detalles_Cita { get; set; }
    }
}
