//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_Cita
    {
        public Detalles_Cita()
        {
            this.Resultado_examen = new HashSet<Resultado_examen>();
        }
    
        public int idDetalle { get; set; }
        public int idCita { get; set; }
        public string Detalles { get; set; }
        public decimal costo { get; set; }
        public bool Active { get; set; }
    
        public virtual Citas Citas { get; set; }
        public virtual ICollection<Resultado_examen> Resultado_examen { get; set; }
    }
}
