//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public Noticia()
        {
            this.Paciente = new HashSet<Paciente>();
        }
    
        public int idNoticia { get; set; }
        public int idDoctor { get; set; }
        public string Titulo { get; set; }
        public byte[] Imagen { get; set; }
        public string Texto { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual ICollection<Paciente> Paciente { get; set; }
    }
}
