//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Citas = new HashSet<Citas>();
            this.Lista_examenes = new HashSet<Lista_examenes>();
            this.Noticia = new HashSet<Noticia>();
        }
    
        public int idPaciente { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual ICollection<Lista_examenes> Lista_examenes { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Noticia> Noticia { get; set; }
    }
}
