//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado_examen
    {
        public int idResultado { get; set; }
        public int idDetalle { get; set; }
        public byte[] Resultado { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Active { get; set; }
        public string tipo { get; set; }
    
        public virtual Detalles_Cita Detalles_Cita { get; set; }
    }
}
